version: "3"
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "81:80"
        volumes:
            - .:/var/www/html
        # depends_on:
        #     - db
        networks:
            - my-network

    # db:
    #     image: mysql:8.0
    #     ports:
    #         - "3306:3306"
    #     volumes:
    #         - ./mysql:/var/lib/mysql
    #     environment:
    #         MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    #         MYSQL_DATABASE: ${DB_DATABASE}
    #         MYSQL_USER: ${DB_USERNAME}
    #         MYSQL_PASSWORD: ${DB_PASSWORD}
    #     networks:
    #         - my-network

    nodejs:
        image: wiwatsrt/docker-laravel-nodejs
        volumes:
            - ./www:/var/www
        networks:
            - my-network

networks:
    my-network:
        driver: bridge
