version: "3"
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        command: sh -c "chown -R www-data:www-data /var/www/html/storage/logs && chmod -R 775 /var/www/html/storage/logs && apache2-foreground"
    db:
        image: mysql:8.0
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        command: --skip-grant-tables --skip-networking --skip-host-cache --skip-name-resolve --explicit_defaults_for_timestamp=1 --init-file /docker-entrypoint-initdb.d/reset.sql

    nodejs:
        image: wiwatsrt/docker-laravel-nodejs
        volumes:
            - ./www:/var/www
